### ISSUE TITLE
Any solution on [json.exception.parse_error.101]?

### ISSUE THREAD

**Issue by Seong-heum** [YeeCY/SMPLpp#1]
>> ./smplpp

[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'v'
sizes() called on undefined Tensor (sizes at /pytorch/c10/core/UndefinedTensorImpl.cpp:12)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f64538a2441 in /usr/local/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f64538a1d7a in /usr/local/lib/libc10.so)
frame #2: c10::UndefinedTensorImpl::sizes() const + 0x6f (0x7f645389b62f in /usr/local/lib/libc10.so)
frame #3: at::Tensor::sizes() const + 0x27 (0x4e54b9 in ./smplpp)
frame #4: smpl::LinearBlendSkinning::getVertex() + 0x8e (0x4f0848 in ./smplpp)
frame #5: smpl::SMPL::out(long) + 0x6a (0x4f68d8 in ./smplpp)
frame #6: main + 0x4ce (0x4d396e in ./smplpp)
frame #7: __libc_start_main + 0xf0 (0x7f640f99d830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: _start + 0x29 (0x4d2729 in ./smplpp)

After successfully compiling your code, this is what I got..

1. ../source/main.cpp
std::string modelPath = "../data/smpl_female.json";

In "main.cpp", this program is supposed to get the hard-coded json file.

2. ../data/smpl_female.json
version https://git-lfs.github.com/spec/v1
oid sha256:d861bd0e3d53b9021f98147e39765b894e77b428cdab9f470d038a7ac324a355
size 192829745

When I opened the input file, I wonder if there's anything wrong in the input json file.

**Comment by YeeCY** [comment]
I think it's a Github issue. If you download the zip file instead of cloning my repo, you won't get the 
"lfs" (i.e. Large File Storage). See this discussion for details: https://github.com/git-lfs/git-lfs/issues/903.

By the way, I wonder if it is slow to `git clone` the repo due to "lfs" transmission. Could you please give me feedback if you try to clone it. Moreover, I'd like to update the I/O ports to obtain model from `.npz` other than `.json` soon.

**Comment by Seong-heum** [comment]
Thank you for the information (git-lfs issue)!
