### ISSUE TITLE
Does the code contain data sets and training procedures?

### ISSUE THREAD

**Issue by Tiompcl** [YeeCY/SMPLpp#10]
Does the code contain data sets and training procedures?

**Comment by YeeCY** [comment]
@Tiompcl Sorry for the late reply. I exclude the SMLP data sets in this repo but I provide a link in the README.md to download it from the official website. You can have a look at the link, download the dataset, and then convert it to a `json` format with script: https://github.com/YeeCY/SMPLpp/blob/master/SMPL%2B%2B/scripts/preprocess.py. We just load json file into the C++ code and then produce the mesh. 

As for the training procedures, the answer is NO. Since the author of the paper didn't provide the code and training dataset to reproduce the results, I am not sure how to do that.
