### ISSUE TITLE
Cannot build on Windows 10, VS 2017

### ISSUE THREAD

**Issue by neonguyen1287** [YeeCY/SMPLpp#2]
Hi,

Has anyone tried to build this project in Windows? I got  a bunch of errors as follows:
![1](https://user-images.githubusercontent.com/51726086/60748854-cac5d280-9f46-11e9-82ce-9424ffd924f2.png)
![2](https://user-images.githubusercontent.com/51726086/60748855-cb5e6900-9f46-11e9-8479-1de8109657ca.png)

Do you know how to fix them?

Thank you

**Comment by tmsc5** [comment]
I just tackled this problem today, and what I did was:
I opened the file where the errors are present _(def.h)_ and included stdint.h

The next error you'll get is MSVC not being able to open stdc++fs.lib, I just removed it from the dependencies.

The next (and hopefully last) hurdle is trying to get ahold of the _real_ smpl_female and smpl_male files, since they're supposed to be +100MBs, but due to Github's limitations, all I have is both files being a little more than 100 Bytes.

**Comment by YeeCY** [comment]
@neonguyen1287 Sorry for the late reply. I haven't tested this project on Windows yet. Apparently, there will be some problems if you build it directly in VS.

And thanks for your suggestion @tmsc5. You follow that one to see if it works.

I think there is a bug with `git-lfs`. I will provide the script to generate `json` files from official `pkl` files soon. Try to download the repo instead of cloning it to fetch all the data. 

Thanks for your feedback!

**Comment by YeeCY** [comment]
Close issue since I have uploaded the converter script
